### ISSUE TITLE
Bug: Long word in proposal title doesn't wrap, instead overflows to side on mobile device

### ISSUE THREAD

**Issue by tohrxyz** [aragon/app-legacy#1022]
**Describe the bug**
When browsing aragon app on smartphone, the long word in proposal title overflows to side, causing layout to break (horizontal scroll) instead it should wrap to new line.

**To Reproduce (please complete the following information)**
- Config and flags: [e.g. variable="xyz"]
- Steps to reproduce the behavior:
    1. use mobile device
    2. go to aragon dao website
    3. long word in proposal title overflows

**Current behavior**
Long word in proposal title overflows, adds a horizontal scroll to side.
<img width="414" alt="image" src="https://github.com/aragon/app/assets/103599310/bfefb6f2-3001-4ab9-aa5e-6bdc2a94eb89">

**Expected behavior**
The long word should wrap into new line.

**System (please complete the following information):**
 - OS: iOS 16.6.1
 - Software version not relevant
 - Commit hash: newest production at the time of submitting issue

**Additional context**
No context.

**Comment by Barukimang** [comment]
Hi @tohrxyz 
Thanks for reporting this!
We had not seen this before. Will pass this to our team to fix.

**Comment by tohrxyz** [comment]
@Barukimang Hey, I have opened a PR fixing this issue, it's done in #1023
