### ISSUE TITLE
Bug: Unable to create a DAO on Polygon

### ISSUE THREAD

**Issue by heueristik** [aragon/app-legacy#1179]
This issue was originally posted here https://github.com/aragon/osx/issues/514 by @Oskii

**Describe the bug**
The final step of DAO creation throws the following error:

```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="latestRelease()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at E.makeError (index.js:224:23)
    at E.throwError (index.js:233:20)
    at z.decodeFunctionResult (interface.js:345:23)
    at $.<anonymous> (index.js:293:48)
    at Generator.next (<anonymous>)
    at o (index.js:5:58)
```

*NETWORK UNSUPPORTED

**To Reproduce (please complete the following information)**

1. Go to https://app.aragon.org/#/create
2. Switch your network to Polygon
3. Attempt to deploy a DAO on Polygon with the following parameters

Network: Mainnet
Blockchain: Polygon
Logo: <Add a PNG>
Name: Oscar's Aragon DAO
Summary: I'm just doing this as a test

**Current behavior**

The console throws the following error and a dao is not created

```
*NETWORK UNSUPPORTED
api-stg.vocdoni.net/v2/accounts/0xEe0861faBEdc0BD4E41fe9fE97E6Cd1c7e4B717a:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
network.tsx:62 *NETWORK UNSUPPORTED
api-stg.vocdoni.net/v2/accounts/0xEe0861faBEdc0BD4E41fe9fE97E6Cd1c7e4B717a:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
4createDao.tsx:516 Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="latestRelease()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at E.makeError (index.js:224:23)
    at E.throwError (index.js:233:20)
    at z.decodeFunctionResult (interface.js:345:23)
    at $.<anonymous> (index.js:293:48)
    at Generator.next (<anonymous>)
    at o (index.js:5:58)
```

**Expected behavior**

A DAO creation transaction should be created via my Metamask wallet. 

**System (please complete the following information):**

- OS: [e.g. Windows 11 Pro]
- Software version [Google Chrome Version 120.0.6099.71 (Official Build) (64-bit)]
- Metamask [11.7.0]

**Comment by Oskii** [comment]
@Michael-A-Heuer thank you for pulling my issue over to the correct spot - much appreciated :)

**Comment by Barukimang** [comment]
Hi @Oskii Thanks for reporting this! Could you give me some more details?

- Did you want to create Token Holders or a Multsig Members DAO?
- The logs show a Vocdoni error. Did you select gassless voting somewhere?

**Comment by Oskii** [comment]
Hi @Barukimang I chose the Token Holders DAO, and I did not select gassless voting to my knowledge.

**Comment by Barukimang** [comment]
Okay, not sure what happened. Just created a Token Holders DAO at Polygon using Windows 11/ Chrome/ Metamask: https://app.aragon.org/#/daos/polygon/0x537256318f7b556b9e4f7556d3e8c26e512ba5c3/dashboard

Could you perhaps try again to see whether it works now?

**Comment by Oskii** [comment]
Hey @Barukimang it worked after a few minutes of trying every 30 seconds or so. It eventually just worked as expected. I imagine this could point to an RPC issue?
