### ISSUE TITLE
Bug: Token validation error on DAO creation form

### ISSUE THREAD

**Issue by selankon** [aragon/app-legacy#1214]
**Describe the bug**
If you add a valid wrapped token on the DAO creation form, and you go forward and back, the validation fail and oyu cannot go forward. 

Then you need to force run the validation again to get the correct validation (for example deleting a letter of the address and write it again) 

**To Reproduce (please complete the following information)**
- Steps to reproduce the behavior:
    1. Go to create DAO form on the Define membership step
    2. Paste an existing valid wrapped token
    3. Go forward and go back
    4. Token validation will fail
    5. Delete a letter of the address and write it again to see how validation pass this time

**Expected behavior**
Validation should pass again if you go back. Or best, don't run the validation again if is already done.

**Comment by jasonttian** [comment]
I would like to fix this isssue.
Let me know if you are interested.
Thx.

**Comment by Barukimang** [comment]
@selankon only seeing this now, thanks for reporting this! 

@jasonttian wlcm to submit a fix if you like! Gotta say we don't have a bounty program, so it would be a voluntary contribution.
