### ISSUE TITLE
Bug: Filter by members is not handled on the graphql api

### ISSUE THREAD

**Issue by octavioamu** [aragon/app-legacy#1336]
**Describe the bug**

Seems the filter by "members" on https://app.aragon.org/ is not handled on the graphql api for the orderBy field also happening with "most proposals" filter.
My guess this is because the orderby filter is not setting "networks" default when data.stats.members data.stats.proposalsCreated  and is trying to filter network null

Query being done on the FE reproduced on postman
<img width="1114" alt="image" src="https://github.com/aragon/app/assets/1358093/525d1c8d-8260-47f3-84d1-e22374c9f20f">

**To Reproduce (please complete the following information)**
- Steps to reproduce the behavior:
    1. go to https://app.aragon.org/
    2. scroll to the list of daos
    3. click the orderby drowpdown and select by members or proposals.
    4. not result funds (api claiming network cannot be null) 

**Current behavior**
no results
**Expected behavior**
showing results

**System (please complete the following information):**
 - OS: [e.g. Fedora 35]
 - Software version [e.g. Docker 8, Node 14.19.1]
 - Commit hash [e.g. e84617d]

**Additional context**
Important to notice if you pre select networks on the filter modal the order works fine, possible quick solution of this would be just preselect all networks by default 

https://github.com/aragon/app/blob/2d51138771a48456d01825b8aa89c54621639388/src/containers/daoFilterModal/index.tsx#L23
```
"networks":["ethereum", "polygon", "arbitrum", "base"],

```
Added networks to the query and the request resolve fine and order the data by members as requested 
<img width="1099" alt="image" src="https://github.com/aragon/app/assets/1358093/cf545fbd-ce4e-49ae-9afe-a91fac6aa521">

**Comment by Barukimang** [comment]
Hi @octavioamu, thanks for this detailed report! The issue should be resolved now. Does it work at your side?

**Comment by octavioamu** [comment]
Perfect, that was fast. Thanks
