### ISSUE TITLE
Bug: Links validation false positive

### ISSUE THREAD

**Issue by sembrestels** [aragon/app-legacy#767]
**Describe the bug**

The Links form do not accept long TLD such as `.software`.

**To Reproduce (please complete the following information)**
- Start the steps to create a new DAO in https://app.aragon.org
- Write `https://blossom.software` in the Link section of your DAO
- See the error

![Screenshot from 2023-03-01 17-45-57](https://user-images.githubusercontent.com/931684/222208591-07b83f95-c2bf-4efc-9516-479833612469.png)

**Comment by Barukimang** [comment]
Hi Sam!

Sorry for the late response and thanks for reporting this Bug!

We fixed the issue:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/16764792/231090351-e4a7fe5b-e15d-4615-bb81-0e14dce8f34a.png">
