### ISSUE TITLE
Bug: Unable to access previously created DAO url

### ISSUE THREAD

**Issue by konjoinfinity** [aragon/app-legacy#860]
**Describe the bug**
We are unable to access the polygon DAO we created last year at: https://aragon.org/reautydao

**To Reproduce (please complete the following information)**

- Steps to reproduce the behavior:
    1. Open a browser and navigate to https://aragon.org/reautydao

**Current behavior**
<img width="914" alt="Screen Shot 2023-05-28 at 2 17 15 PM" src="https://github.com/aragon/app/assets/46323883/af462041-97c3-4eca-84bb-e48a87e145a7">

**Expected behavior**
The ReautyDAO app dashboard should show up.

**System (please complete the following information):**
 - MacOS: Monterey 12.6.1
 - Attempted on Chrome and Brave

**Additional context**
Have the urls changed, if so what is the new url for the DAO?

Thanks,

**Comment by Barukimang** [comment]
Hi @konjoinfinity !

We have disabled ENS names for Polygon, since ENS itself hasn't been deployed on Polygon, so the URLs have changed.

The easiest way to find back your DAO is to search in the 'DAOs created list' with your 'Creator address' at this dashboard: https://dune.com/aragonproject/aragon-app-polygon-main-dashboard

**Comment by konjoinfinity** [comment]
This dune chart only shows Polygon DAO's that were created after 2023-03-27. Our DAO was created in the fall/winter of 2022.

**Comment by konjoinfinity** [comment]
Are polygon DAOs created before 03-27-2023 inaccessible? If not, please advise. Thanks

**Comment by Barukimang** [comment]
@konjoinfinity sorry missed your last messages. Seems like the DAO was created Aragon Client instead of our new Aragon App! You can find it here: https://client.aragon.org/?#/reautydao/

We recommend using our new App however since it has active Developer support.
