### ISSUE TITLE
Bug: deprecated vite plugin

### ISSUE THREAD

**Issue by selankon** [aragon/app-legacy#934]
**Describe the bug**

Deprecated vite plugin [`plugin-react-refresh`](https://www.npmjs.com/package/@vitejs/plugin-react-refresh) in favor [`plugin-react`](https://www.npmjs.com/package/@vitejs/plugin-react).

Sometimes, while developing the react refresh does not work properly. For example, changing some component or adding a className perform a browser refresh but the page is not updated until Vite is restarted. The cause could be related to this deprecated plugin. 

**To Reproduce (please complete the following information)**

1. Start `yarn dev`
2. Do changes on a component, such adding a class or move it on other side.
3. After browser refresh check if the change is done
4. Sometimes the refresh doesn't perform the change until Vite is restarted. 

**Current behavior**

Refresh doesn't update the page until vite restart

**Expected behavior**

Every browser refresh should update the DOM.

**Comment by Barukimang** [comment]
Thanks for reporting this @selankon ! @jamesej & @Fabricevladimir do you think we should update the plugin?

**Comment by Barukimang** [comment]
Update @selankon: the plugin will be updated, grateful for 👁️ -ing this!
